version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/front/
    overwrite: yes
file_exist_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777

hooks:
  ApplicationStart:
    - location: script/deploy.sh
      timeout: 600
      runas: ubuntu
