name: front-ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Npm Install and Build
        run: |
          npm install
          npm run build --if-present

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Get Dist
          path: |
            dist

  

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-region: ap-northeast-2
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#
#      - name: Upload Build file
#        run: aws s3 cp --region ap-northeast-2 ./${{ steps.file.outputs.filename }} s3://deploy/${{ steps.file.outputs.filename }}
#
#      - name: Create AWS codedeploy
#        run: aws deploy create-deployment
#          --application-name Git-action-stag
#          --deployment-config-name CodeDeployDefault.AllAtOnce
#          --deployment-group-name git-action-stage-group
#          --s3-location bucket=deploy,key=${{ steps.file.outputs.filename }},bundleType=zip
